In [77]:
import numpy as np

In [81]:
# 1D Array
arr = np.array([1, 2, 3, 4])

# 2D Array (Matrix)
matrix = np.array([
    [1, 2],
    [3, 4]
])
arr


array([1, 2, 3, 4])

In [82]:
matrix

array([[1, 2],
       [3, 4]])

In [83]:
arr = np.array([1, 2, 3, 4])

print(arr * 2)     # Multiply all elements
print(arr + 5)     # Add to all elements
print(arr ** 2)    # Square each element

[2 4 6 8]
[6 7 8 9]
[ 1  4  9 16]


In [84]:
arr = np.array([1, 2, 3, 4, 5])

print(np.mean(arr))   # Average
print(np.sum(arr))    # Sum
print(np.max(arr))    # Max value
print(np.min(arr))    # Min value

3.0
15
5
1


In [85]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

print(np.dot(a, b))  # Matrix multiplication

[[19 22]
 [43 50]]


In [59]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [58]:
np.arange(0,11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [60]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [61]:
np.linspace(0,20,10)

array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
       11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ])

In [62]:
np.random.rand(10)

array([0.86620232, 0.31552421, 0.90653395, 0.00137097, 0.57548998,
       0.47452438, 0.27205127, 0.26839872, 0.98711439, 0.92971622])

In [63]:
np.random.seed(20)
np.random.rand(10)

array([0.5881308 , 0.89771373, 0.89153073, 0.81583748, 0.03588959,
       0.69175758, 0.37868094, 0.51851095, 0.65795147, 0.19385022])

In [64]:
np.random.randint(1,20,5)

array([17,  7,  7, 17, 10], dtype=int32)

In [65]:
arr = np.arange(25)

In [66]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [67]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [68]:
arr.max()

np.int64(24)

In [69]:
arr[0:4]

array([0, 1, 2, 3])

In [70]:
arr[4:]

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20,
       21, 22, 23, 24])

In [71]:
arr[:]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [72]:
arr_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [73]:
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [74]:
arr_2d.shape

(3, 3)

In [75]:
arr_2d[0]

array([1, 2, 3])

In [76]:
arr_2d[0][0]

np.int64(1)